name: healthregistries.forresearch
domain: http://healthregistries.forresearch.no
project: Health Registries for Research (HRR), national e-infrastructure & data processing
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md
redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]
timezone: GB
permalink: /blog/:year/:month/:day/:title
# pygments: true
gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
  - jemoji
  - jekyll-mentions
